export const componentdata = [
  {
    cardname: "Hero Sections",
    components: [
      {
        variant: "Simple centered",
        jsRequired: true,
        codeString: "<p>Navigation</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "Split with navbar",
        jsRequired: true,
        codeString: "<p>Hello image</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "With angled image on right",
        jsRequired: true,
        codeString: "<p>Hello</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "With app screenshot",
        jsRequired: true,
        codeString: "<p>Navigation</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "With sign-in form",
        jsRequired: true,
        codeString: "<p>Hello image</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "With sign up and media content",
        jsRequired: true,
        codeString: "<p>Hello</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "Card with background image",
        jsRequired: true,
        codeString: "<p>Navigation</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "Dark with illustration",
        jsRequired: true,
        codeString: "<p>Hello image</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "Split with screenshot",
        jsRequired: true,
        codeString: "<p>Hello</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
    ],
  },
  {
    cardname: "Feature Sections",
    components: [
      {
        variant: "Alternative side-by-side with images",
        jsRequired: true,
        codeString: "<p>Navigation</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "Centered 2x2 grid",
        jsRequired: true,
        codeString: "<p>Hello image</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "With feature grid list",
        jsRequired: true,
        codeString: "<p>Hello</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "With feature list",
        jsRequired: true,
        codeString: "<p>Navigation</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "Offset 2x2 grid",
        jsRequired: true,
        codeString: "<p>Hello image</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "Simple three-column",
        jsRequired: true,
        codeString: "<p>Hello</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "Alternating with optional testimonial",
        jsRequired: true,
        codeString: "<p>Navigation</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "4x2 grid on brand",
        jsRequired: true,
        codeString: "<p>Hello image</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "With large screenshot",
        jsRequired: true,
        codeString: "<p>Hello</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "Grid with offset icons",
        jsRequired: true,
        codeString: "<p>Hello</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
    ],
  },
  {
    cardname: "Headers",
    components: [
      {
        variant: "Centered with bottom border",
        jsRequired: true,
        codeString: "<p>Navigation</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "Simple links centered",
        jsRequired: true,
        codeString: "<p>Hello image</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "Simple links on left",
        jsRequired: true,
        codeString: "<p>Hello</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "With full-width flyouts",
        jsRequired: true,
        codeString: "<p>Navigation</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
      {
        variant: "Simple branded with stacked links",
        jsRequired: true,
        codeString: "<p>Hello image</p>",
        variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
      },
    ],
  },
];
// {
//   cardname: "Stacked Layouts",
//   components: [
//     {
//       variant: "Light nav with bottom border",
//       jsRequired: true,
//       codeString: "<p>Navigation</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "Light nav on gray background",
//       jsRequired: true,
//       codeString: "<p>Hello image</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "Dark nav with white page header",
//       jsRequired: true,
//       codeString: "<p>Hello</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "Branded nav with compact white page header",
//       jsRequired: true,
//       codeString: "<p>Navigation</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "Dark nav with overlap",
//       jsRequired: true,
//       codeString: "<p>Navigation</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "Brand nav with overlap",
//       jsRequired: true,
//       codeString: "<p>Hello image</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "Branded nav with white page header",
//       jsRequired: true,
//       codeString: "<p>Hello</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "Dark nav with compact white page header",
//       jsRequired: true,
//       codeString: "<p>Navigation</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "Two-row navigation with overlap",
//       jsRequired: true,
//       codeString: "<p>Hello image</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//   ],
// },
// {
//   cardname: "Page Headings",
//   components: [
//     {
//       variant: "With actions",
//       jsRequired: true,
//       codeString: "<p>Navigation</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "With actions on dark",
//       jsRequired: true,
//       codeString: "<p>Hello image</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "With actions and breadcrumbs",
//       jsRequired: true,
//       codeString: "<p>Hello</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "With actions and breadcrumbs on dark",
//       jsRequired: true,
//       codeString: "<p>Navigation</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "With meta and actions",
//       jsRequired: true,
//       codeString: "<p>Navigation</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "With meta and actions on dark",
//       jsRequired: true,
//       codeString: "<p>Hello image</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "Card with avatar and stats",
//       jsRequired: true,
//       codeString: "<p>Hello</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "With meta, actions, and breadcrumbs",
//       jsRequired: true,
//       codeString: "<p>Navigation</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//     {
//       variant: "With meta, actions, and breadcrumbs on dark",
//       jsRequired: true,
//       codeString: "<p>Hello image</p>",
//       variantImg: "/img/Marketing/pagesections/Herosections/variant1.png",
//     },
//   ],
// },
