const colors = require("tailwindcss/colors");
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/layout/**/*.{js,ts,jsx,tsx}",
    "./src/views/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontSize: {
        homeHero: ["56px", "1.2"],
        pageHero: ["50px", "1.2"],
        heading2: ["45px", "1.2"],
        heading3: ["38px", "1.2"],
        fontTypeA: ["22px", "1.2"],
        fontTypeB: ["17px", "1.2"],
        fontTypeC: ["15px", "1.2"],
        fontTypeD: ["21px", "1.4"],
      },
      colors: {
        primary: "#006CFB",
        secondary: "#39C4FF",
        body: "#868E95",
        white: "#FFFFFF",
        themeBlack: "#222831",
        lightBlue: "#F2F8FF",
        bgLight: "#F5F7FA",
        lightWhite: "#9ca3af",
        planeBlue: "#e5f0ff",
        cloudBurst: "#393E46",
        footer: "#7E868D",
        "secondary-light": "#e9f8fb",
        "theme-gray": "#F2F5F5",
        paragraph: "#4E5556",
        "paragraph-light": "#4D5B5B",
        teal: colors.teal,
        cyan: colors.cyan,
      },
      backgroundImage: {
        heroHome: "url('/img/home/hero-bg.png')",
        banner2: "url('/img/icons/banner-icon2.svg')",
        banner3: "url('/img/icons/banner-icon3.svg')",
        quote: "url('/img/icons/quote.svg')",
        quote: "url('/img/icons/quote.svg')",
        prop1: "url('/img/icons/section-prop1.svg')",
        prop2: "url('/img/icons/section-prop2.svg')",
        prop3: "url('/img/icons/section-prop3.svg')",
        prop4: "url('/img/icons/section-prop4.svg')",
      },
    },
  },
  plugins: [],
};
